In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("IRIS.csv")
data1=data.copy()

In [4]:
#Q1
#A
ten_rows=data1.head(10)
data1.shape
data1.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [5]:
#B
typea="Iris-virginica"
selected_data1=data1.query("petal_length>4.5 and species==@typea")
selected_data1

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
107           7.3          2.9           6.3          1.8  Iris-virginica
108           6.7          2.5           5.8          1.8  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
110           6.5          3.2           5.1          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
112           6.8          3.0           5.5          2.1  Iris-virginica
113           5.7          2.5           5.0          2.0  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
115           6.4          3.2           5.3          2.3  Iris-virginica
116           6.5          3.0           5.5          1.8  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [6]:
#C
data1.groupby("species").agg(
    avg_sepal_length=("sepal_length","mean"),
    max_petal_width=("petal_width","max"),
    std_sepal_width=("sepal_width","std")
)

                 avg_sepal_length  max_petal_width  std_sepal_width
species
Iris-setosa                 5.006              0.6         0.381024
Iris-versicolor             5.936              1.8         0.313798
Iris-virginica              6.588              2.5         0.322497

In [36]:
#D
data1.assign(petal_ratio=data["petal_length"]/data["petal_width"])
data1.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [31]:
#Q2
data_titanic=pd.read_csv("Titanic-Dataset.csv")

In [32]:
#A
selected_columns=data_titanic[["Name","Sex","Age","Fare","Survived"]]

In [33]:
#B
selected_columns[(selected_columns["Sex"]=="female") & (selected_columns["Fare"]>30)]

,Name,Sex,Age,Fare,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,1
25,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,31.3875,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,146.5208,1
...,...,...,...,...,...
853,"Lines, Miss. Mary Conover",female,16.0,39.4000,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,164.8667,1
863,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,69.5500,0
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,52.5542,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,83.1583,1

In [34]:
data_titanic.groupby("Pclass").agg(
    survival_rate=("Survived","mean"),
    avg_fare=("Fare","mean"),
    average_age=("Age","mean")
)

        survival_rate   avg_fare  average_age
Pclass
1            0.629630  84.154687    38.233441
2            0.472826  20.662183    29.877630
3            0.242363  13.675550    25.140620